/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedUsersRouteRouteImport } from './routes/_authenticated/users/route'
import { Route as AuthenticatedRolesRouteRouteImport } from './routes/_authenticated/roles/route'
import { Route as AuthenticatedOrganizationsRouteRouteImport } from './routes/_authenticated/organizations/route'
import { Route as AuthenticatedLoanFollowupAgentRouteRouteImport } from './routes/_authenticated/loan-followup-agent/route'
import { Route as AuthenticatedManageRoleRoleIdRouteRouteImport } from './routes/_authenticated/manage-role/$roleId/route'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRouteRoute = AuthenticatedUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRouteRoute = AuthenticatedRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationsRouteRoute =
  AuthenticatedOrganizationsRouteRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoanFollowupAgentRouteRoute =
  AuthenticatedLoanFollowupAgentRouteRouteImport.update({
    id: '/loan-followup-agent',
    path: '/loan-followup-agent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManageRoleRoleIdRouteRoute =
  AuthenticatedManageRoleRoleIdRouteRouteImport.update({
    id: '/manage-role/$roleId',
    path: '/manage-role/$roleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/loan-followup-agent': typeof AuthenticatedLoanFollowupAgentRouteRoute
  '/organizations': typeof AuthenticatedOrganizationsRouteRoute
  '/roles': typeof AuthenticatedRolesRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/manage-role/$roleId': typeof AuthenticatedManageRoleRoleIdRouteRoute
}
export interface FileRoutesByTo {
  '/loan-followup-agent': typeof AuthenticatedLoanFollowupAgentRouteRoute
  '/organizations': typeof AuthenticatedOrganizationsRouteRoute
  '/roles': typeof AuthenticatedRolesRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/manage-role/$roleId': typeof AuthenticatedManageRoleRoleIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/loan-followup-agent': typeof AuthenticatedLoanFollowupAgentRouteRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRouteRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRouteRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/manage-role/$roleId': typeof AuthenticatedManageRoleRoleIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/loan-followup-agent'
    | '/organizations'
    | '/roles'
    | '/users'
    | '/sign-in'
    | '/sign-in-2'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/manage-role/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/loan-followup-agent'
    | '/organizations'
    | '/roles'
    | '/users'
    | '/sign-in'
    | '/sign-in-2'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/manage-role/$roleId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/loan-followup-agent'
    | '/_authenticated/organizations'
    | '/_authenticated/roles'
    | '/_authenticated/users'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/manage-role/$roleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loan-followup-agent': {
      id: '/_authenticated/loan-followup-agent'
      path: '/loan-followup-agent'
      fullPath: '/loan-followup-agent'
      preLoaderRoute: typeof AuthenticatedLoanFollowupAgentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-role/$roleId': {
      id: '/_authenticated/manage-role/$roleId'
      path: '/manage-role/$roleId'
      fullPath: '/manage-role/$roleId'
      preLoaderRoute: typeof AuthenticatedManageRoleRoleIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLoanFollowupAgentRouteRoute: typeof AuthenticatedLoanFollowupAgentRouteRoute
  AuthenticatedOrganizationsRouteRoute: typeof AuthenticatedOrganizationsRouteRoute
  AuthenticatedRolesRouteRoute: typeof AuthenticatedRolesRouteRoute
  AuthenticatedUsersRouteRoute: typeof AuthenticatedUsersRouteRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedManageRoleRoleIdRouteRoute: typeof AuthenticatedManageRoleRoleIdRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLoanFollowupAgentRouteRoute:
    AuthenticatedLoanFollowupAgentRouteRoute,
  AuthenticatedOrganizationsRouteRoute: AuthenticatedOrganizationsRouteRoute,
  AuthenticatedRolesRouteRoute: AuthenticatedRolesRouteRoute,
  AuthenticatedUsersRouteRoute: AuthenticatedUsersRouteRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedManageRoleRoleIdRouteRoute:
    AuthenticatedManageRoleRoleIdRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
